version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: es
    environment:
    #   - node.name=es`WD
    #   - cluster.name=es-docker-cluster
    #   - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es
    #   - bootstrap.memory_lock=true
    #   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  
  backend:
    restart: always
    container_name: back
    #command : bash -c "python manage.py runserver 0.0.0.0:8000"
    # env_file:12
    #   - ./project/settings.ini
    build:
      context: ./backout/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - es
    networks:
      - elastic

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./stonks-fe/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - elastic

# volumes:
#   data01:
#     driver: local
#   data02:
#     driver: local
#   data03:
#     driver: local

networks:
  elastic:
    driver: bridge

